Texture2D   diffuseMap : register(t0);
Texture2D   normalMap : register(t1);
Texture2D   detailsMap : register(t2);
Texture2D   emissiveMap : register(t3);
TextureCube IBLDiffuse : register(t4);
TextureCube IBLSpecular : register(t5);
Texture2D   IBLIntegration : register(t6);
Texture2D   Mask1 : register(t7);
Texture2D   Mask2 : register(t8);